// js/constants/music-songs.js
// Static list of 2000s songs for the MusicPlayer

export const MUSIC_SONGS = [
  { title: "3 Doors Down - Here Without You", url: "/songs/3_doors_down-here_without_you.mp3" },
  { title: "50 Cent - In Da Club", url: "/songs/50_cent-in_da_club.mp3" },
  { title: "Avenged Sevenfold - Bat Country", url: "/songs/Avenged Sevenfold - Bat Country [Official Music Video].mp3" },
  { title: "Band of Horses - The Funeral", url: "/songs/Band of Horses - The Funeral [OFFICIAL VIDEO].mp3" },
  { title: "Beyoncé - Irreplaceable", url: "/songs/Beyoncé - Irreplaceable-trim.mp3" },
  { title: "Bowling For Soup - Girl All The Bad Guys Want", url: "/songs/Bowling For Soup - Girl All The Bad Guys Want (Official Video).mp3" },
  { title: "Bright Eyes - First Day of My Life", url: "/songs/Bright Eyes - First Day of My Life [Official Music Video].mp3" },
  { title: "Britney Spears - Toxic", url: "/songs/Britney Spears - Toxic (Official HD Video).mp3" },
  { title: "Coheed and Cambria - Welcome Home", url: "/songs/Coheed and Cambria - Welcome Home.mp3" },
  { title: "D4L - Laffy Taffy", url: "/songs/D4L - Laffy Taffy (Official Video)-trim.mp3" },
  { title: "Fall Out Boy - Sugar, We're Goin Down", url: "/songs/Fall Out Boy - Sugar, We're Goin Down (Official Music Video).mp3" },
  { title: "Gavin DeGraw - I Don't Want To Be", url: "/songs/Gavin DeGraw - I Don't Want To Be (Official Video).mp3" },
  { title: "HIM - Wings Of A Butterfly HD", url: "/songs/HIM - Wings Of A Butterfly HD (OFFICIAL MUSIC VIDEO).mp3" },
  { title: "Hinder - Lips Of An Angel", url: "/songs/Hinder - Lips Of An Angel (Official Music Video).mp3" },
  { title: "Juvenile - Slow Motion ft. Soulja Slim", url: "/songs/Juvenile - Slow Motion ft. Soulja Slim.mp3" },
  { title: "Mae - Embers and Envelopes", url: "/songs/Mae - Embers and Envelopes (Official Music Video) [128 kbps].mp3" },
  { title: "Maria Mena - You're the Only One", url: "/songs/Maria Mena - You're the only one.mp3" },
  { title: "Matisyahu - King Without A Crown", url: "/songs/Matisyahu - King Without A Crown.mp3" },
  { title: "Modest Mouse - Florida", url: "/songs/Modest Mouse - Florida.mp3" },
  { title: "My Chemical Romance - Teenagers", url: "/songs/My Chemical Romance - Teenagers [Official Music Video] [4K].mp3" },
  { title: "New Found Glory - My Friends Over You", url: "/songs/New Found Glory - My Friends Over You (Official Music Video).mp3" },
  { title: "Outkast - Ms. Jackson", url: "/songs/Outkast - Ms. Jackson (Official HD Video).mp3" },
  { title: "Papa Roach - Last Resort", url: "/songs/Papa Roach - Last Resort.mp3" },
  { title: "Ray J - Sexy Can I", url: "/songs/Ray J - Sexy Can I (feat. Yung Berg) [Official Video].mp3" },
  { title: "Rihanna - We Ride", url: "/songs/Rihanna - We Ride.mp3" },
  { title: "Sean Kingston - Beautiful Girls", url: "/songs/Sean Kingston - Beautiful Girls (Official HD Video).mp3" },
  { title: "Soulja Boy Tell'em - Crank That", url: "/songs/Soulja Boy Tell'em - Crank That (Soulja Boy) (Official Music Video).mp3" },
  { title: "Taylor Swift - Love Story", url: "/songs/Taylor Swift - Love Story.mp3" },
  { title: "Tegan and Sara - Walking With A Ghost", url: "/songs/Tegan and Sara - Walking With A Ghost [Official Music Video].mp3" },
  { title: "The Darkness - I Believe In A Thing Called Love", url: "/songs/The Darkness - I Believe In A Thing Called Love (Official Music Video) [HD]-trim.mp3" },
];
