-- ============================================================
-- Superseded by 2026_10_05_walktober_ladders.sql. Do not run.
--
-- This file first added Count von Count as a 7-day (then 10-day) streak
-- under walktober_2026_streak_7 / _10. That key is now a streak ladder
-- tier, and Count von Count moved to walktober_2026_full_month.
-- The ladders file renames the old row if this one was already applied.
-- Date: 2026-10-04
-- ============================================================
